### ISSUE TITLE
Missing Dimensionalization for longitudinal coordinate of rudder

### ISSUE THREAD

**Issue by nikpau** [ShipMMG/shipmmg#31]
Hi and thanks for your implementation!

I recently started my own implementation of the MMG model of ship maneuvering and came across yours for comparison. However, from my understanding in Eq (18) in the [original implementation](https://link.springer.com/article/10.1007/s00773-014-0293-y), they use the re-dimensionalized x-coordinate of the rudder `x_R` to calculate the yaw moment around midship `N_R`. 

In your code below, you keep the non-dimentionalized version of just -0.5 rather than -0.5*L_pp, which also yields to satisfactory results in the turning tests and ZigZag maneuvers. 
https://github.com/ShipMMG/shipmmg/blob/a5b877a3e1ae25487495bcfc7e58e0b403c99f53/shipmmg/mmg_3dof.py#L905

If I redimensionalize the variable in my code, surprisingly the resulting turning circles are way too small.

Also if I just leave out the -0.5 in your code, the results are nearly unaffected, which -by intuition- should not be the case. Do you know why this is? 

Thanks in advance!

**Comment by taiga4112** [comment]
Thank you for your comment.
Firstly, your comment is right. Based on the original paper, this formula must be modified as follows:

```python
N_R = -(-0.5*L_pp + a_H * x_H) * F_N * np.cos(δ) 
```

However, as you already mentioned, the resulting turning circles are way too small.
In practical, we should re-estimate the parameters of each coefficient from the result of trajectory or tank test.

**Comment by nikpau** [comment]
Thanks for your comment. I already suspected that this might be the case. I find it a real pity, that the original turning circles cannot be reproduced using their original implementation. 
Thank you anyway for your kind help!
